version: '3.7'

services:
  protector:
    build:
      context: .
    depends_on:
      - mongo
    restart: on-failure
    environment:
      DB_URI: 'mongodb://Kunaldiwan:kunaldiwan@mongo'

  mongo:
    image: 'mongo:latest'
    volumes:
      - 'mongo_protector:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: Kunaldiwan
      MONGO_INITDB_ROOT_PASSWORD: kunaldiwan

volumes:
  mongo_kunaldiwan:
